[package]
name = "chapter_1_2"
version = "0.1.0"
authors = ["Ben Doerr <ben.doerr@luminsmart.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = "0.5.17"
specs = "0.15.1"
specs-derive = "0.4.0"
